Revert "Clean up Buffer11."
Fails Clang-win because of std::forward

..\..\third_party\angle\src\libANGLE/Error.h(60,40):  error: no matching function for call to 'forward'

BUG=598944
BUG=angleproject:1327
BUG=angleproject:1310

This reverts commit 041d678b4764484386f934df927f00a5df48a351.

Change-Id: I9fb0685cd01090b1faf8417ffa3c9b49eeb4510e
Reviewed-on: https://chromium-review.googlesource.com/336040
Reviewed-by: Jamie Madill <jmadill@chromium.org>